### ISSUE TITLE
Pretrained PoseNet weight

### ISSUE THREAD

**Issue by LINFF1023** [327926791/PoseNet#1]
HI!!!!!! Thank you for your contribution.
How to download pretrained PoseNet weight?
Looking forward to your reply.

**Comment by 327926791** [comment]
> HI!!!!!! Thank you for your contribution. How to download pretrained PoseNet weight? Looking forward to your reply.

Please try the following:
wget https://vision.in.tum.de/webarchive/hazirbas/poselstm-pytorch/places-googlenet.pickle
